Updated the firmware to newer stuff

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,7 +1,7 @@
 name: PR Lint keyboards
 
-permissions:
-  contents: read
+#permissions:
+#  contents: read
 
 on:
   pull_request:
@@ -18,7 +18,7 @@ jobs:
     - name: Disable safe.directory check
       run : git config --global --add safe.directory '*'
 
-    - uses: actions/checkout@v4
+    - uses: actions/checkout@v3
       with:
         fetch-depth: 0
 
@@ -27,9 +27,7 @@ jobs:
 
     - name: Get changed files
       id: file_changes
-      uses: tj-actions/changed-files@v44
-      with:
-        use_rest_api: true
+      uses: tj-actions/changed-files@v37
 
     - name: Print info
       run: |
@@ -64,12 +62,10 @@ jobs:
 
         qmk format-text ${{ steps.file_changes.outputs.all_changed_files}} || true
         for file in ${{ steps.file_changes.outputs.all_changed_files}}; do
-          if [[ -f $file ]]; then
-            if ! git diff --quiet $file; then
-              echo "File '${file}' Requires Formatting"
-              echo "::error file=${file}::Requires Formatting"
-              exit_code=$(($exit_code + 1))
-            fi
+          if ! git diff --quiet $file; then
+            echo "File '${file}' Requires Formatting"
+            echo "::error file=${file}::Requires Formatting"
+            exit_code=$(($exit_code + 1))
           fi
         done
 
@@ -78,10 +74,31 @@ jobs:
         fi
         exit $exit_code
 
-    - name: Verify keyboard aliases
+    - name: Verify at most one added keyboard
       if: always()
       shell: 'bash {0}'
       run: |
         git reset --hard
         git clean -xfd
-        qmk ci-validate-aliases
+
+        # Get the keyboard list and count for the target branch
+        git checkout -f ${{ github.base_ref }}
+        git pull --ff-only
+        QMK_KEYBOARDS_BASE=$(qmk list-keyboards)
+        QMK_KEYBOARDS_BASE_COUNT=$(qmk list-keyboards | wc -l)
+
+        # Get the keyboard list and count for the PR
+        git checkout -f ${{ github.head_ref }}
+        git merge --no-commit --squash ${{ github.base_ref }}
+        QMK_KEYBOARDS_PR=$(qmk list-keyboards)
+        QMK_KEYBOARDS_PR_COUNT=$(qmk list-keyboards | wc -l)
+
+        echo "::group::Keyboards changes in this PR"
+        diff -d -U 0 <(echo "$QMK_KEYBOARDS_BASE") <(echo "$QMK_KEYBOARDS_PR") | grep -vE '^(---|\+\+\+|@@)' | sed -e 's@^-@Removed: @g' -e 's@^+@  Added: @g'
+        echo "::endgroup::"
+
+        if [[ $QMK_KEYBOARDS_PR_COUNT -gt $(($QMK_KEYBOARDS_BASE_COUNT + 1)) ]]; then
+            echo "More than one keyboard added in this PR -- see the PR Checklist."
+            echo "::error::More than one keyboard added in this PR -- see the PR Checklist."
+            exit 1
+        fi
